# Generated by Django 6.0.1 on 2026-04-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("resumo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("tecnologias", models.CharField(blank=True, max_length=200)),
                ("github_url", models.URLField(blank=True)),
                ("demo_url", models.URLField(blank=True)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="projetos/"),
                ),
            ],
        ),
    ]
